name: Build LaTeX document
on: [push]
jobs:
    build_latex:
        permissions:
            contents: write

        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v4
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                  root_file: cv_7.tex
                  continue_on_error: true
                  args: -f -interaction=nonstopmode -pdf
            - name: Copy
              run: |
                  mkdir out
                  cp ./cv_7.pdf ./out/cv_7.pdf
            - uses: actions/upload-artifact@v4
              with:
                  name: cv
                  path: out/cv_7.pdf
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  CLEAN: true
                  SINGLE_COMMIT: true
                  FOLDER: out
                  GIT_CONFIG_NAME: daniel-jakob
                  GIT_CONFIG_EMAIL: danieljakob1307@gmail.com
